spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # jpa설정
  jpa:
    hibernate:
      ddl-auto: update
