# .github/workflows/your-workflow-name.yml

name: Build Backend with Remote Frontend and Deploy (Remote Docker Build - Corrected)

on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 실행 가능
  repository_dispatch:
    types: [frontend-update]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 백엔드 코드 체크아웃
      - name: Checkout Backend Repository
        uses: actions/checkout@v4

      # 2. 프론트엔드 코드 체크아웃
      - name: Checkout Frontend Repository
        uses: actions/checkout@v4
        with:
          repository: Capstone-Memoria/Memoria-Front # 실제 프론트엔드 레포지토리 경로
          path: frontend
          ref: main # 필요시 브랜치 변경

      # 3. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # --- Node.js 캐시 설정 ---
      - name: Cache Node.js modules
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ./frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. 프론트엔드 의존성 설치 및 빌드
      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      # 5. 빌드된 프론트엔드 파일을 Spring Boot static 폴더로 복사
      - name: Copy frontend build to Spring Boot static resources
        run: |
          echo "Copying frontend build from $(pwd)/frontend/dist to $(pwd)/src/main/resources/static"
          rm -rf ./src/main/resources/static/*
          mkdir -p ./src/main/resources/static
          cp -r ./frontend/dist/* ./src/main/resources/static/

      # 6. Java 환경 설정
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      # --- Gradle 캐시 설정 ---
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 7. gradlew 파일에 실행 권한 부여
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 8. 백엔드 빌드 (Gradle bootJar)
      # 이 단계 후 ./build/libs/ 에 .jar 파일이 생성됩니다.
      - name: Build Backend with Gradle
        run: ./gradlew bootJar

      # 9. SSH 키 생성 및 설정
      - name: Create SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem
          echo "SSH key created and permissions set"

      # 10. 서버를 known_hosts에 추가
      - name: Add Known Host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          echo "Added ${{ secrets.SERVER_HOST }} to known_hosts"

      # 11. SCP로 Dockerfile 및 JAR 파일 전송
      # Dockerfile과 build/libs/*.jar 파일을 원격 서버 배포 경로로 직접 전송합니다.
      - name: Transfer Build Context to Remote Server
        run: |
          scp -i ./private-key.pem -P ${{ secrets.SERVER_PORT }} \
            ./Dockerfile \
            ./build/libs/*.jar \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH }}/
          echo "Dockerfile and JAR file transferred to remote server's deploy path (${{ secrets.DEPLOY_PATH }})"

      # 12. SSH로 원격 서버 접속 후 Docker 이미지 빌드 및 실행
      # 'set -e' 추가: 스크립트 내 명령어 실패 시 즉시 중단
      # Dockerfile에서 'COPY *.jar app.jar'를 사용한다고 가정합니다.
      - name: Build and Deploy on Remote Server
        run: |
          ssh -i ./private-key.pem -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            set -e # 명령어 실패 시 즉시 중단하여 이후 단계 실행 방지

            # 배포 경로로 이동
            cd ${{ secrets.DEPLOY_PATH }}
            echo "Current directory on remote: $(pwd)"

            # 원격 서버에서 Docker 이미지 빌드 (Dockerfile은 현재 디렉토리에 있어야 함)
            echo "Building Docker image on remote server..."
            docker build -t memoria:latest . # 현재 디렉토리('.')를 빌드 컨텍스트로 사용

            # 기존 컨테이너 중지 및 삭제 (오류 무시)
            echo "Stopping and removing existing container..."
            docker stop memoria || true
            docker rm memoria || true

            # 새로 빌드된 이미지로 Docker 컨테이너 실행
            echo "Running new Docker container..."
            docker run -d --name memoria \
              --network postgres_postgres_net \
              -p 2873:8080 \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              memoria:latest # 새로 빌드된 이미지 태그 사용

            echo "Docker container deployed successfully on remote server using remotely built image"
          EOF

      # 13. 정리
      - name: Cleanup
        run: |
          rm -f ./private-key.pem
          echo "Cleaned up local SSH key"
